channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.2.2
  - numpy>=1.20.2
  - pandas>=1.1.3
  - gseapy>=0.9.5
  - lifelines>=0.21.0
  - rpy2>=3.4.5
  - seaborn>=0.11.1
  - scikit-learn>=0.4.6
  - statsmodels>=0.11.1
  - umap-learn>=0.3.9
